[package]
name = "macroquad_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "macroquad_utils"
path = "src/lib.rs"
proc-macro = true

[dependencies]
darling = "0.20.8"
proc-macro2 = "1.0.82"
quote = "1.0.36"
rust-embed = "8.3.0"
syn = "2.0.61"